export const initialData = {
  debts: [
    {
      id: "1",
      name: "Credit Card",
      description: "High interest credit card debt",
      type: "credit-card",
      initialAmount: 5000,
      paidAmount: 1200,
      interestRate: 18.99,
      monthlyPayment: 150,
      payments: [
        {
          id: "p1",
          amount: 500,
          date: "2023-12-15T00:00:00.000Z",
          note: "Initial payment",
        },
        {
          id: "p2",
          amount: 350,
          date: "2024-01-15T00:00:00.000Z",
          note: "Monthly payment",
        },
        {
          id: "p3",
          amount: 350,
          date: "2024-02-15T00:00:00.000Z",
          note: "Monthly payment",
        },
      ],
      createdAt: "2023-12-01T00:00:00.000Z",
    },
    {
      id: "2",
      name: "Student Loan",
      description: "Federal student loan",
      type: "student-loan",
      initialAmount: 25000,
      paidAmount: 5000,
      interestRate: 4.5,
      monthlyPayment: 300,
      payments: [
        {
          id: "p4",
          amount: 2500,
          date: "2023-11-10T00:00:00.000Z",
          note: "Initial payment",
        },
        {
          id: "p5",
          amount: 1250,
          date: "2023-12-10T00:00:00.000Z",
          note: "Monthly payment",
        },
        {
          id: "p6",
          amount: 1250,
          date: "2024-01-10T00:00:00.000Z",
          note: "Monthly payment",
        },
      ],
      createdAt: "2023-11-01T00:00:00.000Z",
    },
    {
      id: "3",
      name: "Car Loan",
      description: "Auto loan for vehicle purchase",
      type: "auto-loan",
      initialAmount: 15000,
      paidAmount: 3000,
      interestRate: 3.9,
      monthlyPayment: 275,
      payments: [
        {
          id: "p7",
          amount: 1500,
          date: "2023-10-20T00:00:00.000Z",
          note: "Down payment",
        },
        {
          id: "p8",
          amount: 750,
          date: "2023-11-20T00:00:00.000Z",
          note: "Monthly payment",
        },
        {
          id: "p9",
          amount: 750,
          date: "2023-12-20T00:00:00.000Z",
          note: "Monthly payment",
        },
      ],
      createdAt: "2023-10-01T00:00:00.000Z",
    },
  ],
  achievements: [
    {
      id: "1",
      name: "First Debt Added",
      description: "Added your first debt to track",
      category: "getting started",
      points: 10,
      unlocked: true,
      unlockedAt: "2023-10-01T00:00:00.000Z",
    },
    {
      id: "2",
      name: "First Payment",
      description: "Made your first debt payment",
      category: "payments",
      points: 15,
      unlocked: true,
      unlockedAt: "2023-10-20T00:00:00.000Z",
    },
    {
      id: "3",
      name: "25% Debt-Free",
      description: "Paid off 25% of your total debt",
      category: "milestones",
      points: 25,
      unlocked: true,
      unlockedAt: "2024-01-15T00:00:00.000Z",
      progressBased: true,
      currentProgress: 25,
      targetProgress: 25,
    },
    {
      id: "4",
      name: "Halfway There",
      description: "Paid off 50% of your total debt",
      category: "milestones",
      points: 50,
      unlocked: false,
      unlockedAt: null,
      progressBased: true,
      currentProgress: 25,
      targetProgress: 50,
    },
    {
      id: "5",
      name: "Almost There",
      description: "Paid off 75% of your total debt",
      category: "milestones",
      points: 75,
      unlocked: false,
      unlockedAt: null,
      progressBased: true,
      currentProgress: 25,
      targetProgress: 75,
    },
    {
      id: "6",
      name: "Debt Freedom",
      description: "Paid off 100% of your debt. Congratulations!",
      category: "milestones",
      points: 100,
      unlocked: false,
      unlockedAt: null,
      progressBased: true,
      currentProgress: 25,
      targetProgress: 100,
    },
    {
      id: "7",
      name: "Consistency King",
      description: "Made payments for 3 consecutive months",
      category: "consistency",
      points: 30,
      unlocked: true,
      unlockedAt: "2024-01-20T00:00:00.000Z",
      progressBased: true,
      currentProgress: 3,
      targetProgress: 3,
    },
    {
      id: "8",
      name: "Early Bird",
      description: "Made an early payment on a debt",
      category: "payments",
      points: 20,
      unlocked: false,
      unlockedAt: null,
    },
    {
      id: "9",
      name: "Extra Mile",
      description: "Made an extra payment beyond the minimum",
      category: "payments",
      points: 25,
      unlocked: true,
      unlockedAt: "2023-12-15T00:00:00.000Z",
    },
    {
      id: "10",
      name: "First Debt Conquered",
      description: "Completely paid off your first debt",
      category: "milestones",
      points: 50,
      unlocked: false,
      unlockedAt: null,
    },
  ],
}
